export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_ERRORS = 'UPDATE_ERRORS';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
